### ISSUE TITLE
[Bug]: Data for this config hasn't been loaded yet

### ISSUE THREAD

**Issue by Thunderrock424242** [Fuzss/forgeconfigscreens#13]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.0

### Notes (Required)

i have a modpack with over 150 mods and it says this when i try to edit some configs this does happen with most of them
![Screenshot 2023-07-27 195551](https://github.com/Fuzss/forgeconfigscreens/assets/119463825/50045334-5974-4afc-9118-bc90e94bfa92)

**Comment by Thunderrock424242** [comment]
Is it because my pack is too big?

**Comment by soda77** [comment]
Disabling the "Night Config Fixes" mod resolves this issue for me, but I have no idea why this would be the case.

**Comment by Fuzss** [comment]
Thank you! Fixed in v8.0.2, Night Config Fixes was indeed the issue.
I guess that's what you get for having too many mods; they start breaking each other lol

**Comment by SettingDust** [comment]
Can you port this fix to 1.18.2?

**Comment by KyrDerz** [comment]
> Thank you! Fixed in v8.0.2, Night Config Fixes was indeed the issue. I guess that's what you get for having too many mods; they start breaking each other lol

It is still an issue for 1.18.2
Lot's of people still play on it with modpacks like BMC2.
What were the fixes?
